# Generated by Django 5.2.4 on 2025-08-12 19:42

from django.db import migrations

def create_default_table(apps, schema_editor):
    TableType = apps.get_model('api', 'TableTypeModel') 
    TableType.objects.bulk_create([ 
        TableType(big_blind=2, small_blind=1, min_buy_in=100, max_buy_in=400), 
        TableType(big_blind=10, small_blind=5, min_buy_in=500, max_buy_in=2000), 
        TableType(big_blind=20, small_blind=10, min_buy_in=1000, max_buy_in=4000), 
        TableType(big_blind=100, small_blind=50, min_buy_in=5000, max_buy_in=20000), 
        TableType(big_blind=500, small_blind=250, min_buy_in=25000, max_buy_in=100000), 
        TableType(big_blind=1000, small_blind=500, min_buy_in=50000, max_buy_in=200000), 
        ])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_table),
    ]
