# Generated by Django 5.2.4 on 2025-08-13 21:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_default_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chips_claimed',
            field=models.DateTimeField(default=api.models.get_default_chips_claimed),
        ),
    ]
