# Generated by Django 5.2.4 on 2025-08-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_chips_claimed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermodel',
            old_name='chip_in_play',
            new_name='chips_in_play',
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='num_of_players',
            field=models.PositiveIntegerField(default=0, max_length=6),
        ),
    ]
