# Generated by Django 5.2.4 on 2025-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_chip_in_play_playermodel_chips_in_play_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='community_cards',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='open_seats',
            field=models.CharField(default='123456', null=True),
        ),
    ]
