# Generated by Django 5.2.4 on 2025-09-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_gamemodel_community_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='cards',
            field=models.CharField(max_length=157, null=True),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
    ]
