# Generated by Django 5.2.4 on 2026-07-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gamemodel_cards_gamemodel_game_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermodel',
            old_name='total_round_bet',
            new_name='total_bet',
        ),
        migrations.RemoveField(
            model_name='potmodel',
            name='closed',
        ),
        migrations.AddField(
            model_name='potmodel',
            name='cap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potmodel',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
