# Generated by Django 5.2.4 on 2026-07-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_total_round_bet_playermodel_total_bet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='street_bet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
